### ISSUE TITLE
"Sum" policy would not work with tipping bucket

### ISSUE THREAD

**Issue by user2684** [egeoffrey/egeoffrey-controller#23]
Ref. https://forum.egeoffrey.com/topic/77/tipping-bucket

**Comment by eporocrail** [comment]
Measures get in as usual and at any time, hourly aggregates are the sum of those values per hour, daily aggregates are the sum of the hourly measures. 
This solution as you proposed is for the user the most easy one which will lead to useful information.

My own solution is to report every hour the amount fallen in that hour plus the amount fallen in the last 24 hours.
But this is not something the average user would implement.

**Comment by user2684** [comment]
Go it thanks! For my own reference reverse engineering the code, this is the way it works right now:
- aggregation by hour: the values of the selected timeframe are retrieved from the database, the following statistics are calculated if configured: avg, min_max, rate, sum, count, count_unique
- aggregation by day: the **hourly averages** of the selected timeframe are retrieved from the database, the following statistics are calculated if configured: avg, min_max, rate, sum, count, count_unique

Aggregation by hour is ok overall since directly working on the collected values.
Aggregation by day is ok for the following: avg, min_max, rate since working on the hourly averages (by design and to avoid spikes or invalid values to invalidate the entire statistics, the calculation is performed on hourly averages and not on the values). This approach is because a single query to the database is performed for calculating all the derived metrics.

This means sum, count, count_unique are those with a wrong behaviour. 
- day/sum should be based on hour/sum and not hour/avg
- day/count should be based on hour/count and not hour/avg
- day/count_unique has no much sense at all

Possibile solutions:
1. Specify in the aggregate policy the series the aggregation has to be based upon 
1. Automatically select the right series based on the aggregation requested

**Comment by user2684** [comment]
- A static `keys_to_read` variable mapping for each statistics which key to read has been added to `calculate()` in `controller/db`
- a FOR cycle has been introduced for each statistics which is:
    - setting key_to_read based on the static mapping
    - check if the key has been already read (a cache has been introduced)
    - If not in cache the key is read and cached
    - Values are processed as usual and results are written into the destination keys as before
 
This approach avoids changes in the definition of the calculations (managed `controller/hub`) and hence in its configuration file. Sooner or later hub.yml has to be split in multiple files to allow the gui to build up the configuration wizard so additional customisations from the users could be introduced by then, right now the mapping is static. 

@eporocrail egeoffrey-controller v1.3-3 should be available with this change. I'd recommend to backup your database before proceeding (just tar the `data/database/data` directory somewhere else)
