### ISSUE TITLE
WARNING: Unable to connect to egeoffrey-gateway:443

### ISSUE THREAD

**Issue by eadgbear** [egeoffrey/egeoffrey-controller#27]
Fresh Install on a Raspberry Pi W.

After the install I'm unable to access the Web GUI at all. Installation succeeded and all services show as running through `status` but I get "Connection Refused" when trying to use a browser to connect.

Full Warning is:
```
 WARNING: Unable to connect to egeoffrey-gateway:443 - Traceback (most recent call last):|  File "sdk/python/module/helpers/mqtt_client.py", line 51, in __connect|    self.gateway.connect(self.module.gateway_hostname, self.module.gateway_port)|  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 937, in connect|    return self.reconnect()|  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect|    sock = self._create_socket_connection()|  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection|    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)|  File "/usr/lib/python2.7/socket.py", line 553, in create_connection|    for res in getaddrinfo(host, port, 0, SOCK_STREAM):|gaierror: [Errno -5] No address associated with hostname|
```

**Comment by user2684** [comment]
Hi, thanks for reporting it. May you please double check egeoffrey-gateway is running as well? If so the hostname should be made discoverable by the underlaying docker system. Couple of additional information you can get and share:
- Operating system version
- Docker version (docker -v)
- the output of `egeoffrey-cli logs` 10-20 seconds after having run `egeoffrey-cli start`
Thanks!

**Comment by eadgbear** [comment]
Looks like there's some sort of port interference between eGeoffrey and the MySensors Gateway (built using instructions [here](https://www.mysensors.org/build/raspberry).

Couldn't quite track down which one it was that caused the GUI to fail to start.

**Comment by user2684** [comment]
Oh I see, in case you need to change any port eGeoffrey is using yo can play with the `.env` and `docker-compose.yml` files. I will also need to detail this process in the docs (https://github.com/egeoffrey/docs.egeoffrey.com/issues/8)
